import translateFactory from "@minus5/legenda.lib/src/translate_factory";

export const translate = translateFactory({
  ma: "markets",
  li: "lines",
  ou: "outcomes",
  na: "name",
  id: "id",
  od: "odds",
  re: "result",
  st: "status",
  fs: "fixtures",
  me: "meta",
  os: "offers",
  ho: "home",
  aw: "away",
  ss: "sports",
  cs: "categories",
  ts: "tournaments",
  sn: "seasons",
  rs: "rounds",
  mi: "main",
  sa: "startsAt",
  so: "stopped",
  rm: "removed",
  sc: "scores",
  pr: "progress",
  se: "server",
  to: "total",
  po: "points",
  ps: "periods",
});
